project:
  type: website
  
execute:
    freeze: auto

website:
  title: "Valentin Lauret"
  navbar:
    title: "Valentin Lauret"
    background: "#1d3557"
    foreground: "#F1FAEE"
    search: true
    left:
      - href: about.qmd
        text: Home
      - skills.qmd
      - publications.qmd
    tools:
      - icon: github
        href: https://github.com/valentinlauret 
      - icon: twitter
        href: https://bsky.app/profile/valentinlauret.bsky.social

      
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    




