---
title: "Publications"
subtitle: "You can check my [Google Scholar](https://scholar.google.com/citations?user=hbi_zlMAAAAJ&hl=en) profile."
title-block-banner: "#F1FAEE"
title-block-banner-color: "#1D3557"
enableEmoji: true
lightbox: true
page-navigation: true
margin-left: 2pt
margin-right: 2pt
---

### BOOK CHAPTER & THESIS MANUSCRIPT

1. Gimenez, O., Louvrier, J., **Lauret, V.**, & Santostasi, N. L. (2022). Studying Species Demography and Distribution in Natural Conditions: Hidden Markov Models. In N. Peyrard & O. Gimenez (Eds.), Statistical Approaches for Hidden Variables in Ecology (pp. 45–60). Wiley. [https://doi.org/10.1002/9781119902799.ch3](https://doi.org/10.1002/9781119902799.ch3)
👉 [PDF](/doc/bookHMM.pdf)

2. **Lauret, V.** (2021). _Étudier les suivis écologiques dans les Aires Marines Protégées de Méditerranée française : Une approche interdisciplinaire autour du grand dauphin_ [PhD thesis, Université Montpellier]. [https://tel.archives-ouvertes.fr/tel-03553990](https://tel.archives-ouvertes.fr/tel-03553990)
👉 [PDF for English version](/doc/LATEZ_ENG_lowres.pdf)

### PUBLISHED PAPERS

<ol reversed>
  <li>**Lauret, V.**, Gimenez, O., Labach, H., & Lescureux, N. (2024). Smokescreen or groundwork? The paradox of ecological monitoring in the management of Marine Protected Areas. Marine Policy, 170, 106383. [https://doi.org/10.1016/j.marpol.2024.106383](https://doi.org/10.1016/j.marpol.2024.106383)</li>

\ 
  <li>**Lauret, V.** , Labach, H., David, L., Authier, M., & Gimenez, O. (2023). Using integrated multispecies occupancy models to map co-occurrence between bottlenose dolphins and fisheries in the Gulf of Lion, French Mediterranean Sea. _Oikos_, 11. [https://onlinelibrary.wiley.com/doi/10.1111/oik.10270](https://onlinelibrary.wiley.com/doi/10.1111/oik.10270)</li>

\ 
 <li>Couturier, T., Bauduin, S., Astruc, G., Blanck, A., Canonne, C., Chambert, T., Chiffard, J., Cosquer, A., Cubaynes, S., Curtet, L., Dortel, E., Drouet-Hoguet, N., Duchamp, C., Francesiaz, C., Grente, O., Jailloux, A., Kervellec, M., **Lauret, V.**, Lebreton, JD.,  Louvrier, J., Marescot, L., Mathevet, R., Navas, ML., Perrot, C., Poulet, N., Quenette, PY., Salas, M., Souchay, G., Vanpé, C.,  Besnard, A., Gimenez, O. (2023). Building spaces of interactions between researchers and managers: Case studies with wildlife monitoring and conservation in France. _Ecological Solutions and Evidence_, 4. [https://doi.org/10.1002/2688-8319.12245](https://doi.org/10.1002/2688-8319.12245).</li>

\
  <li>**Lauret, V**., Labach, H., Turek, D., Laran, S., & Gimenez, O. (2022). Integrated spatial models foster complementarity between monitoring programmes in producing large scale bottlenose dolphin indicators. _Animal Conservation_, 11. [https://doi.org/10.1111/acv.12815](https://doi.org/10.1111/acv.12815)</li>

\
  <li>**Lauret, V**., Labach, H., Authier, M., & Gimenez, O. (2021). Using single visits into integrated occupancy models to make the most of existing monitoring programs. _Ecology_. [https://doi.org/10.1002/ecy.3535](https://doi.org/10.1002/ecy.3535)</li>

\
  <li>Labach, H., Azzinari, C., Barbier, M., Cesarini, C., Daniel, B., David, L., Dhermain, F., Di-Méglio, N., Guichard, B., Jourdan, J., **Lauret, V**., Robert, N., Roul, M., Tomasi, N., & Gimenez, O. (2021). Distribution and abundance of common bottlenose dolphin (Tursiops truncatus) over the French Mediterranean continental shelf. _Marine Mammal Science_.  [https://doi.org/10.1111/mms.12874](https://doi.org/10.1111/mms.12874)</li>

\
  <li>**Lauret, V**., Delibes-Mateos, M., Mougeot, F., & Arroyo-Lopez, B. (2020). Understanding conservation conflicts associated with rodent outbreaks in farmland areas. _Ambio_, _49_(5), 1122–1133. [https://doi.org/10.1007/s13280-019-01256-0](https://doi.org/10.1007/s13280-019-01256-0)
👉 [PDF](/doc/rodent2019.pdf)</li>

\
  <li>Wan, H. Y., McGarigal, K., Ganey, J. L., **Lauret, V.** , Timm, B. C., & Cushman, S. A. (2017). Meta-replication reveals nonstationarity in multi-scale habitat selection of Mexican Spotted Owl. _The Condor_, _119_(4), 641–658. [https://doi.org/10.1650/CONDOR-17-32.1](https://doi.org/10.1650/CONDOR-17-32.1)
👉 [PDF](/doc/condor2017.pdf)</li>

\
  <li>Louvrier, J., Duchamp, C., **Lauret, V**., Marboutin, E., Cubaynes, S., Choquet, R., Miquel, C., & Gimenez, O. (2017). Mapping and explaining wolf recolonization in France using dynamic occupancy models and opportunistic data. _Ecography_. [http://onlinelibrary.wiley.com/doi/10.1111/ecog.02874/full](http://onlinelibrary.wiley.com/doi/10.1111/ecog.02874/full)</li>
</ol>